In [49]:

import pandas as pd

# Load the public project dataset
file_path = "/content/solution-lens-projects-2026-10-26 (1).csv"
df = pd.read_csv(file_path)

# Display the first five records
display(df.head())

,Code,Title,Status,Schedule,LGA,Location,Responsible MDA,Sector,Progress (%),Approved cost (NGN),Started,Target completion,Completed,Last update
0,PRJ-2024-000005,Reconstruction Of Some Selected Streets In Oni...,In progress,NaN,Ogbaru,"Fegge I, Onitsha South, Anambra",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-08T11:34:11.143Z
1,PRJ-2024-000007,"Construction of Premier Road, Onitsha",In progress,NaN,Onitsha South,"Inland Town III, Onitsha North, Anambra",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-08T11:46:31.336Z
2,PRJ-2024-000008,Remedial Works on Onitsha – Owerri Road,In progress,NaN,Onitsha South,"G.R.A, Onitsha North, Anambra",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-08T11:57:27.773Z
3,PRJ-2024-000010,Reconstruction of Ugwunwanosike Ogidi Building...,In progress,NaN,Idemili North,"Ogidi I, Idemili North, Anambra",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-08T12:02:30.396Z
4,PRJ-2024-000011,"Erosion Control Works at Oba, Along Onitsha - ...",In progress,NaN,Idemili South,"Oba I, Idemili South, Anambra",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-08T12:04:33.539Z

In [50]:

# Check the dataset size
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# Display all column names
print("\nColumn names:")
print(df.columns.tolist())

# Count missing values in each column
print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False))

Number of rows: 201
Number of columns: 14

Column names:
['Code', 'Title', 'Status', 'Schedule', 'LGA', 'Location', 'Responsible MDA', 'Sector', 'Progress (%)', 'Approved cost (NGN)', 'Started', 'Target completion', 'Completed', 'Last update']

Missing values:
Target completion      201
Sector                 201
Completed              201
Approved cost (NGN)    200
Started                200
Responsible MDA        154
Progress (%)           154
Schedule               123
Last update             47
LGA                      1
Location                 1
Status                   0
Code                     0
Title                    0
dtype: int64

In [51]:

# Calculate missing values and percentages
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().mean() * 100).round(2),
    "Available Count": df.notnull().sum()
})

missing_summary = missing_summary.sort_values(
    by="Missing Percentage",
    ascending=False
)

display(missing_summary)

                     Missing Count  Missing Percentage  Available Count
Target completion              201              100.00                0
Sector                         201              100.00                0
Completed                      201              100.00                0
Approved cost (NGN)            200               99.50                1
Started                        200               99.50                1
Responsible MDA                154               76.62               47
Progress (%)                   154               76.62               47
Schedule                       123               61.19               78
Last update                     47               23.38              154
LGA                              1                0.50              200
Location                         1                0.50              200
Status                           0                0.00              201
Code                             0                0.00              201
Title                            0                0.00              201

In [52]:

# 1. Inspect data types and available values
print("DATA TYPES AND AVAILABLE VALUES")
df.info()

# 2. Check reported progress values
print("\nPROGRESS VALUES")
print(df["Progress (%)"].describe())

# 3. Check project status categories
print("\nPROJECT STATUS CATEGORIES")
print(df["Status"].value_counts(dropna=False))

# 4. Check duplicate project titles
print("\nDUPLICATE PROJECT TITLES")
print("Number of repeated titles:",
      df["Title"].duplicated(keep=False).sum())

# 5. Inspect schedule values
print("\nSCHEDULE CATEGORIES")
print(df["Schedule"].value_counts(dropna=False))

# 6. Inspect project counts by LGA
print("\nPROJECTS BY LGA")
print(df["LGA"].value_counts(dropna=False))

DATA TYPES AND AVAILABLE VALUES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Code                 201 non-null    object
 1   Title                201 non-null    object
 2   Status               201 non-null    object
 3   Schedule             78 non-null     object
 4   LGA                  200 non-null    object
 5   Location             200 non-null    object
 6   Responsible MDA      47 non-null     object
 7   Sector               0 non-null      float64
 8   Progress (%)         47 non-null     float64
 9   Approved cost (NGN)  1 non-null      float64
 10  Started              1 non-null      object
 11  Target completion    0 non-null      float64
 12  Completed            0 non-null      float64
 13  Last update          154 non-null    object
dtypes: float64(5), object(9)
memory usage: 22.1+ KB

PROGRESS VALUES
count     47.000000
mean      54.187447
std       36.846016
min        0.000000
25%       28.500000
50%       65.000000
75%       90.000000
max      100.000000
Name: Progress (%), dtype: float64

PROJECT STATUS CATEGORIES
Status
In progress    123
Completed       78
Name: count, dtype: int64

DUPLICATE PROJECT TITLES
Number of repeated titles: 0

SCHEDULE CATEGORIES
Schedule
NaN          123
Delivered     78
Name: count, dtype: int64

PROJECTS BY LGA
LGA
Awka South       70
Aguata           18
Nnewi North      13
Anaocha          11
Ogbaru           10
Orumba North     10
Anambra East      9
Onitsha South     9
Idemili South     8
Oyi               8
Awka North        6
Njikoka           6
Idemili North     5
Dunukofia         4
Ihiala            4
Orumba South      3
Ayamelum          2
Onitsha North     2
Ekwusigo          1
NaN               1
Anambra West      1
Name: count, dtype: int64

In [53]:

# Select projects that have reported progress
progress_df = df[df["Progress (%)"].notna()].copy()

# Compare reported progress with project status
print("PROGRESS BY PROJECT STATUS")

display(
    progress_df.groupby("Status")["Progress (%)"].agg(
        ["count", "mean", "median", "min", "max"]
    ).round(2)
)

# Find projects whose progress may need investigation
print("\nPROJECTS REQUIRING STATUS REVIEW")

review_df = df[
    ((df["Status"] == "Completed") &
     (df["Progress (%)"] < 100)) |
    ((df["Status"] == "In progress") &
     (df["Progress (%)"] == 100))
]

display(
    review_df[
        ["Code", "Title", "Status", "LGA", "Progress (%)"]
    ]
)

print("\nNumber of projects flagged for review:",
      len(review_df))

# List all projects with reported progress
print("\nALL PROJECTS WITH REPORTED PROGRESS")

display(
    progress_df[
        ["Code", "Title", "Status", "LGA", "Progress (%)"]
    ].sort_values("Progress (%)", ascending=True)
)

PROGRESS BY PROJECT STATUS

             count   mean  median  min    max
Status
In progress     47  54.19    65.0  0.0  100.0

PROJECTS REQUIRING STATUS REVIEW

,Code,Title,Status,LGA,Progress (%)
199,PRJ-2026-000085,Reclamation/rechannelization and remediation o...,In progress,Njikoka,100.0

Number of projects flagged for review: 1

ALL PROJECTS WITH REPORTED PROGRESS

,Code,Title,Status,LGA,Progress (%)
158,PRJ-2026-000044,Construction of the runway at the Anambra Aero...,In progress,Orumba North,0.00
165,PRJ-2026-000051,Construction of additional storm water dischar...,In progress,Awka North,0.00
168,PRJ-2026-000054,Construction of Bright Street and parks 1 & 2,In progress,Onitsha North,0.00
184,PRJ-2026-000070,Construction of Johnson Street and park 3 Onitsha,In progress,Onitsha North,0.00
178,PRJ-2026-000064,Construction of the Ivite-Umueri road to the C...,In progress,Anambra East,0.00
193,PRJ-2026-000079,Construction and dualization of the Aerotropol...,In progress,Orumba North,0.00
200,PRJ-2026-000086,Construction of the acccess road and extension...,In progress,Aguata,0.00
180,PRJ-2026-000066,Construction and dualization of the 7.04km roa...,In progress,Awka South,1.00
171,PRJ-2026-000057,"Aerotropolis taxi way/apron, Ndikelionwu",In progress,Orumba North,5.00
188,PRJ-2026-000074,Construction and dualization of the Aerotropol...,In progress,Orumba North,5.00
163,PRJ-2026-000049,Lot2: construction of airport terminal buildin...,In progress,Orumba North,5.00
157,PRJ-2026-000043,Construction and dualization of 3-3 Nsugbe to ...,In progress,Oyi,27.00
187,PRJ-2026-000073,Construction of additional external works with...,In progress,Awka South,30.00
166,PRJ-2026-000052,Construction of increte finishing on the media...,In progress,Anambra East,30.00
169,PRJ-2026-000055,Beautification of the International Convention...,In progress,Awka South,30.00
185,PRJ-2026-000071,Construction of the 3-side perimeter fence at ...,In progress,Aguata,30.00
173,PRJ-2026-000059,Construction & dualization of Ekwulobia - Ufum...,In progress,Aguata,33.05
194,PRJ-2026-000080,Construction of Ihiala - Umudara - Ndiezike ro...,In progress,Ihiala,35.00
190,PRJ-2026-000076,General external works within the Solution Inn...,In progress,Awka South,40.00
174,PRJ-2026-000060,Supply and installation of integrated ICT infr...,In progress,Awka South,40.00
159,PRJ-2026-000045,Construction and dualization of Ekwulobia to N...,In progress,Aguata,47.26
183,PRJ-2026-000069,Supply and installation of additional furnitur...,In progress,Awka South,50.00
167,PRJ-2026-000053,Construction of access road leading to Seraphi...,In progress,Anambra East,65.00
189,PRJ-2026-000075,Construction of Mbaukwu-Awgu-Amaetiti-Okpeze N...,In progress,Orumba North,65.00
161,PRJ-2026-000047,The supply and installation of electrical appu...,In progress,Awka South,70.00
170,PRJ-2026-000056,The supply and installation of mechanical (lot...,In progress,Awka South,70.00
177,PRJ-2026-000063,Construction of access road to university on t...,In progress,Oyi,70.00
195,PRJ-2026-000081,Rehabilitation of Awkuzu-Igbariam-Anaku link road,In progress,Oyi,75.00
182,PRJ-2026-000068,Construction of Ugwuaku Ibughugbu Osu Umuchu r...,In progress,Aguata,75.00
172,PRJ-2026-000058,Construction of Uga-Amesi-Otikpo road,In progress,Aguata,82.00
175,PRJ-2026-000061,Construction of Ukwuorji Awka Umunechi villiag...,In progress,Awka South,85.00
186,PRJ-2026-000072,Access road road within the Chukwuemeka Odumeg...,In progress,Ihiala,85.00
191,PRJ-2026-000077,Construction of school road with interlocking ...,In progress,Ogbaru,85.00
176,PRJ-2026-000062,Construction of the main building in the perma...,In progress,Awka South,90.00
197,PRJ-2026-000083,Construction of paved areas (kerbs interlockin...,In progress,Awka South,90.00
196,PRJ-2026-000082,Construction of the road connecting St. August...,In progress,Orumba South,90.00
179,PRJ-2026-000065,Construction of Ogboji-Ndiokolo-Ndiokpaleke road,In progress,Orumba South,90.00
181,PRJ-2026-000067,Construction of 16.51km (lot2) Nnewi to Ozubul...,In progress,Nnewi North,90.00
164,PRJ-2026-000050,Construction of Pal juction - Oko- Ogboji road,In progress,Orumba North,92.50
154,PRJ-2026-000040,Construction of Abba junction - Nawgu - Isuani...,In progress,Awka North,95.00
192,PRJ-2026-000078,"Access road road into the Awka dump site Awka,...",In progress,Awka South,95.00
198,PRJ-2026-000084,Constr. of flood water diversion at Ezioko Oru...,In progress,Orumba North,95.00
155,PRJ-2026-000041,Construction of Acha road with interlocking pa...,In progress,Ogbaru,95.00
160,PRJ-2026-000046,The production and installation of 500 pieces ...,In progress,Awka South,95.00
156,PRJ-2026-000042,Construction & dualization of Nwagu - Nnobi - ...,In progress,Anaocha,96.00
162,PRJ-2026-000048,Constr. of solution modern gate at the Chukwue...,In progress,Ihiala,98.00
199,PRJ-2026-000085,Reclamation/rechannelization and remediation o...,In progress,Njikoka,100.00

In [54]:

# Create an audit copy; preserve the original dataset
audit_df = df.copy()

# Create a list of review flags for each project
def identify_issues(row):
    issues = []

    if pd.isna(row["LGA"]):
        issues.append("Missing LGA")

    if pd.isna(row["Progress (%)"]):
        issues.append("Missing progress")

    if pd.isna(row["Responsible MDA"]):
        issues.append("Missing responsible MDA")

    if pd.isna(row["Schedule"]):
        issues.append("Missing schedule")

    if row["Status"] == "In progress" and pd.isna(row["Last update"]):
        issues.append("Missing last update")

    if pd.notna(row["Progress (%)"]):
        if not 0 <= row["Progress (%)"] <= 100:
            issues.append("Progress outside 0-100 range")

        if row["Status"] == "In progress" and row["Progress (%)"] == 100:
            issues.append("Verify status: 100% progress")

        if row["Status"] == "Completed" and row["Progress (%)"] < 100:
            issues.append("Verify status: progress below 100%")

    return "; ".join(issues)

# Apply the checks
audit_df["Review Flags"] = audit_df.apply(identify_issues, axis=1)

# Separate records requiring review
flagged_projects = audit_df[
    audit_df["Review Flags"] != ""
].copy()

# Display the summary
print("Total projects:", len(audit_df))
print("Projects flagged for review:", len(flagged_projects))
print("Projects without these review flags:",
      len(audit_df) - len(flagged_projects))

# View the flagged records
display(
    flagged_projects[
        ["Code", "Title", "Status", "LGA",
         "Progress (%)", "Review Flags"]
    ].head(20)
)

Total projects: 201
Projects flagged for review: 201
Projects without these review flags: 0

,Code,Title,Status,LGA,Progress (%),Review Flags
0,PRJ-2024-000005,Reconstruction Of Some Selected Streets In Oni...,In progress,Ogbaru,NaN,Missing progress; Missing responsible MDA; Mis...
1,PRJ-2024-000007,"Construction of Premier Road, Onitsha",In progress,Onitsha South,NaN,Missing progress; Missing responsible MDA; Mis...
2,PRJ-2024-000008,Remedial Works on Onitsha – Owerri Road,In progress,Onitsha South,NaN,Missing progress; Missing responsible MDA; Mis...
3,PRJ-2024-000010,Reconstruction of Ugwunwanosike Ogidi Building...,In progress,Idemili North,NaN,Missing progress; Missing responsible MDA; Mis...
4,PRJ-2024-000011,"Erosion Control Works at Oba, Along Onitsha - ...",In progress,Idemili South,NaN,Missing progress; Missing responsible MDA; Mis...
5,PRJ-2024-000012,Construction of the Eziagu-Umunze Bye-Pass Road,In progress,Orumba South,NaN,Missing progress; Missing responsible MDA; Mis...
6,PRJ-2024-000013,Construction of The Centre Nnokwa To Awka-Etit...,In progress,Idemili South,NaN,Missing progress; Missing responsible MDA; Mis...
7,PRJ-2024-000014,Construction of Phase 1 Discharge Channel Alon...,In progress,Nnewi North,NaN,Missing progress; Missing responsible MDA; Mis...
8,PRJ-2024-000015,Construction of Access Roads and Parking Lots ...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
9,PRJ-2024-000016,Rehabilitation/Construction of Obi Adimora Spu...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
10,PRJ-2024-000017,Construction of Tarzan Link Road to 33 and Bri...,In progress,Onitsha South,NaN,Missing progress; Missing responsible MDA; Mis...
11,PRJ-2024-000019,Rehabilitation of Roads along Failed Sections ...,In progress,Dunukofia,NaN,Missing progress; Missing responsible MDA; Mis...
12,PRJ-2024-000020,Rehabilitation/Construction of Roads along pil...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
13,PRJ-2024-000022,The Construction of Ekwulobia Flood Control Pr...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
14,PRJ-2024-000023,The Construction of Ekwulobia Flood Control Pr...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
15,PRJ-2024-000024,The Construction of Phase 11 Discharge Channel...,In progress,Nnewi North,NaN,Missing progress; Missing responsible MDA; Mis...
16,PRJ-2024-000025,The Reclamation and Control of Flood and Gully...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
17,PRJ-2024-000027,Dualization And Reconstruction of Amawbia - Ug...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
18,PRJ-2024-000028,The Dualization & Reconstruction of Amawbia- U...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
19,PRJ-2024-000029,The Construction and Installation of Precast C...,In progress,Idemili North,NaN,Missing progress; Missing responsible MDA; Mis...

In [55]:

# Create an audit copy; preserve the original dataset
audit_df = df.copy()

# Create a list of review flags for each project
def identify_issues(row):
    issues = []

    if pd.isna(row["LGA"]):
        issues.append("Missing LGA")

    if pd.isna(row["Progress (%)"]):
        issues.append("Missing progress")

    if pd.isna(row["Responsible MDA"]):
        issues.append("Missing responsible MDA")

    if pd.isna(row["Schedule"]):
        issues.append("Missing schedule")

    if row["Status"] == "In progress" and pd.isna(row["Last update"]):
        issues.append("Missing last update")

    if pd.notna(row["Progress (%)"]):
        if not 0 <= row["Progress (%)"] <= 100:
            issues.append("Progress outside 0-100 range")

        if row["Status"] == "In progress" and row["Progress (%)"] == 100:
            issues.append("Verify status: 100% progress")

        if row["Status"] == "Completed" and row["Progress (%)"] < 100:
            issues.append("Verify status: progress below 100%")

    return "; ".join(issues)

# Apply the checks
audit_df["Review Flags"] = audit_df.apply(identify_issues, axis=1)

# Separate records requiring review
flagged_projects = audit_df[
    audit_df["Review Flags"] != ""
].copy()

# Display the summary
print("Total projects:", len(audit_df))
print("Projects flagged for review:", len(flagged_projects))
print("Projects without these review flags:",
      len(audit_df) - len(flagged_projects))

# View the flagged records
display(
    flagged_projects[
        ["Code", "Title", "Status", "LGA",
         "Progress (%)", "Review Flags"]
    ].head(20)
)

Total projects: 201
Projects flagged for review: 201
Projects without these review flags: 0

,Code,Title,Status,LGA,Progress (%),Review Flags
0,PRJ-2024-000005,Reconstruction Of Some Selected Streets In Oni...,In progress,Ogbaru,NaN,Missing progress; Missing responsible MDA; Mis...
1,PRJ-2024-000007,"Construction of Premier Road, Onitsha",In progress,Onitsha South,NaN,Missing progress; Missing responsible MDA; Mis...
2,PRJ-2024-000008,Remedial Works on Onitsha – Owerri Road,In progress,Onitsha South,NaN,Missing progress; Missing responsible MDA; Mis...
3,PRJ-2024-000010,Reconstruction of Ugwunwanosike Ogidi Building...,In progress,Idemili North,NaN,Missing progress; Missing responsible MDA; Mis...
4,PRJ-2024-000011,"Erosion Control Works at Oba, Along Onitsha - ...",In progress,Idemili South,NaN,Missing progress; Missing responsible MDA; Mis...
5,PRJ-2024-000012,Construction of the Eziagu-Umunze Bye-Pass Road,In progress,Orumba South,NaN,Missing progress; Missing responsible MDA; Mis...
6,PRJ-2024-000013,Construction of The Centre Nnokwa To Awka-Etit...,In progress,Idemili South,NaN,Missing progress; Missing responsible MDA; Mis...
7,PRJ-2024-000014,Construction of Phase 1 Discharge Channel Alon...,In progress,Nnewi North,NaN,Missing progress; Missing responsible MDA; Mis...
8,PRJ-2024-000015,Construction of Access Roads and Parking Lots ...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
9,PRJ-2024-000016,Rehabilitation/Construction of Obi Adimora Spu...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
10,PRJ-2024-000017,Construction of Tarzan Link Road to 33 and Bri...,In progress,Onitsha South,NaN,Missing progress; Missing responsible MDA; Mis...
11,PRJ-2024-000019,Rehabilitation of Roads along Failed Sections ...,In progress,Dunukofia,NaN,Missing progress; Missing responsible MDA; Mis...
12,PRJ-2024-000020,Rehabilitation/Construction of Roads along pil...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
13,PRJ-2024-000022,The Construction of Ekwulobia Flood Control Pr...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
14,PRJ-2024-000023,The Construction of Ekwulobia Flood Control Pr...,In progress,Aguata,NaN,Missing progress; Missing responsible MDA; Mis...
15,PRJ-2024-000024,The Construction of Phase 11 Discharge Channel...,In progress,Nnewi North,NaN,Missing progress; Missing responsible MDA; Mis...
16,PRJ-2024-000025,The Reclamation and Control of Flood and Gully...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
17,PRJ-2024-000027,Dualization And Reconstruction of Amawbia - Ug...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
18,PRJ-2024-000028,The Dualization & Reconstruction of Amawbia- U...,In progress,Awka South,NaN,Missing progress; Missing responsible MDA; Mis...
19,PRJ-2024-000029,The Construction and Installation of Precast C...,In progress,Idemili North,NaN,Missing progress; Missing responsible MDA; Mis...

In [56]:

# Export the complete audit and flagged projects
audit_df.to_csv("anambra_project_audit.csv", index=False)
flagged_projects.to_csv("anambra_flagged_projects.csv", index=False)

# Download the files to your laptop
from google.colab import files

files.download("anambra_project_audit.csv")